INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Arroz', 5.99, 100);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Feijão', 4.50, 200);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Macarrão', 3.75, 150);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Açúcar', 2.99, 180);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Sal', 1.25, 300);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Óleo', 7.80, 120);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Café', 9.90, 250);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Leite', 4.20, 180);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Farinha de Trigo', 3.10, 130);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Manteiga', 8.50, 90);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Refrigerante', 6.50, 100);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Biscoito', 2.50, 210);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Sabão em Pó', 12.30, 80);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Detergente', 2.00, 160);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Shampoo', 15.75, 70);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Condicionador', 16.90, 65);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Papel Higiênico', 10.99, 140);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Sabonete', 2.20, 250);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Creme Dental', 5.30, 190);
INSERT INTO produto (nome, preco, quantidade_estoque) VALUES ('Amaciante', 8.90, 110);
