INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Arroz', 'Arroz Branco 5kg', 25.50, 100);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Feijão', 'Feijão Carioca 1kg', 8.99, 200);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Óleo de Soja', 'Óleo de soja 900ml', 7.50, 150);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Açúcar', 'Açúcar Refinado 1kg', 4.00, 180);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Sal', 'Sal Refinado 1kg', 1.50, 300);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Café', 'Café Torrado e Moído 500g', 14.90, 120);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Macarrão', 'Macarrão Espaguete 500g', 3.75, 250);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Farinha de Trigo', 'Farinha de Trigo 1kg', 5.80, 220);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Leite', 'Leite Integral 1L', 4.99, 100);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Manteiga', 'Manteiga com Sal 200g', 9.50, 80);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Papel Higiênico', 'Papel Higiênico 4 rolos', 12.00, 500);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Sabão em Pó', 'Sabão em Pó 1kg', 10.50, 120);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Amaciante', 'Amaciante de Roupas 2L', 15.00, 90);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Detergente', 'Detergente Líquido 500ml', 2.00, 300);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Escova de Dentes', 'Escova de Dentes Média', 7.00, 80);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Sabonete', 'Sabonete Hidratante 90g', 3.00, 400);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Shampoo', 'Shampoo 350ml', 12.90, 100);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Condicionador', 'Condicionador 350ml', 13.90, 100);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Desodorante', 'Desodorante Roll-on 50ml', 8.00, 150);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Creme Dental', 'Creme Dental 90g', 6.50, 200);